spring:
  application:
    name: quicklink

server:
  port: 8080

aws:
  region: us-east-1

dynamodb:
  table:
    urls: quicklink-urls
    tokens: quicklink-tokens

app:
  short-domain: https://skt.inc
